//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trac_nghiem_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class do_exam
    {
        public Nullable<int> score { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> statrt_time { get; set; }
        public Nullable<System.DateTime> finsh_time { get; set; }
        public long id_exam { get; set; }
        public long id_student { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual user user { get; set; }
    }
}
