//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trac_nghiem_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class do_exam
    {
        [DisplayName("Điểm")]
        public Nullable<double> score { get; set; }
		
        public string chose { get; set; }
		
        [DisplayName("Ghi chú")]
        [DataType(DataType.MultilineText)]
        public string note { get; set; }

        [DisplayName("Thời gian bắt đầu")]
        [DataType(DataType.DateTime)]

        public Nullable<System.DateTime> statrt_time { get; set; }

        [DisplayName("Thời gian kết thúc")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> finsh_time { get; set; }
		
        public long id_exam { get; set; }
        public long id_student { get; set; }
        public long id_question { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual question question { get; set; }
        public virtual students_user students_user { get; set; }
    }
}
