//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trac_nghiem_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class grade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public grade()
        {
            this.subject_grade = new HashSet<subject_grade>();
            this.students_user = new HashSet<students_user>();
        }
    
        public long id_grade { get; set; }
		
        [DisplayName("Lớp")]
        public string name { get; set; }

        [DisplayName("Ngày tạo")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> date_create { get; set; }
		
        public Nullable<long> id_field { get; set; }
    
        public virtual field field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subject_grade> subject_grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<students_user> students_user { get; set; }
    }
}
