//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trac_nghiem_project.Models
{
	using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class manager
    {
        public long id_manager { get; set; }
		
		[DisplayName("Email")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        [DataType(DataType.EmailAddress,ErrorMessage ="Email không đúng định dạng")]
        public string email { get; set; }
		
		[DisplayName("UserName")]
        [Required(ErrorMessage ="Không được bỏ trống")]
        public string username { get; set; }
		
		[DisplayName("Họ và tên")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string name { get; set; }
        public Nullable<long> id_right { get; set; }
		
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        [DataType(DataType.Password)]
        public string password { get; set; }
		
		[DisplayName("Ghi chú")]
        [DataType(DataType.MultilineText)]
        public string note { get; set; }
    
        public virtual right right { get; set; }
    }
}
