//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trac_nghiem_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_bank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public question_bank()
        {
            this.question_bank_questions = new HashSet<question_bank_questions>();
        }
    
        public long id_question_bank { get; set; }
        public long id_subject_grade { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question_bank_questions> question_bank_questions { get; set; }
        public virtual subject_grade subject_grade { get; set; }
    }
}
