//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trac_nghiem_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_bank_questions
    {
        public long id_question_bank { get; set; }
        public long id_question { get; set; }
        public string note { get; set; }
    
        public virtual question_bank question_bank { get; set; }
        public virtual question question { get; set; }
    }
}
