//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trac_nghiem_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class score_of_exam
    {
        public long id_exam { get; set; }
        public long id_student { get; set; }
        public int id_redo { get; set; }
        public Nullable<double> score { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> finish_time { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual students_user students_user { get; set; }
    }
}
