//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trac_nghiem_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_teacher
    {
        public long id_sbject { get; set; }
        public long id_teacher { get; set; }
        public string note { get; set; }
    
        public virtual subject subject { get; set; }
        public virtual user user { get; set; }
    }
}
