//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trac_nghiem_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_student
    {
        public long id_subject_grade { get; set; }
        public long id_student { get; set; }
        public string note { get; set; }
    
        public virtual students_user students_user { get; set; }
        public virtual subject_grade subject_grade { get; set; }
    }
}
