//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trac_nghiem_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.do_exam = new HashSet<do_exam>();
            this.subject_student = new HashSet<subject_student>();
            this.subject_teacher = new HashSet<subject_teacher>();
        }

        public long id_user { get; set; }

        [DisplayName("Tên ng??i dùng")]
        [Required(ErrorMessage ="Không ???c ?? tr?ng")]
        public string username { get; set; }

        [DisplayName("H? và tên")]
        [Required(ErrorMessage = "Không ???c ?? tr?ng")]
        public string name { get; set; }

        [DisplayName("M?t kh?u")]
        [Required(ErrorMessage = "Không ???c ?? tr?ng"),DataType(DataType.Password)]
        public string password { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Không ???c ?? tr?ng"),DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [DisplayName("Avatar")]
        [DataType(DataType.Upload)]
        public string avatar { get; set; }

        [DisplayName("Gi?i tính")]
        public Nullable<bool> gender { get; set; }

        [DisplayName("Ngày sinh")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> birthday { get; set; }

        [DisplayName("Ngày t?o")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> date_create { get; set; }

        //[DisplayName("Quy?n h?n")]
        public Nullable<long> id_right { get; set; }

        //[DisplayName("L?p")]
        public Nullable<long> id_grade { get; set; }

        //[DisplayName("Chuyên ngành")]
        public Nullable<long> id_field { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<do_exam> do_exam { get; set; }

        [DisplayName("Chuyên ngành")]
        public virtual field field { get; set; }

        [DisplayName("L?p")]
        public virtual grade grade { get; set; }

        [DisplayName("Quy?n h?n")]
        public virtual right right { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subject_student> subject_student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subject_teacher> subject_teacher { get; set; }
    }
}
